# Generated by Django 6.0.5 on 2026-05-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('generated_sql', models.TextField()),
                ('safe_sql', models.TextField(blank=True)),
                ('was_blocked', models.BooleanField(default=False)),
                ('block_reason', models.TextField(blank=True)),
                ('row_count', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
